#KnowledgeCast AI - Backend
from fastapi import FastAPI,File,UploadFile,HTTPException
import os
import shutil
from datetime import datetime

app = FastAPI()

@app.get("/")
def home():
    return {"message": "KnowledgeCast AI is running"}

@app.get("/health")
def health_check():
    return {"status": "ok"}


from pydantic import BaseModel

class SummaryRequest(BaseModel):
     topic: str
     duration: int = 5

@app.post("/generate-summary")
def generate_summary(request: SummaryRequest):
     return {
         "topic": request.topic,
         "duration": request.duration,
         "summary": "this will be generated by AI later"
     }



@app.get("/About")
def home():
    return {"project": "KnowledgeCast AI"}



class gr(BaseModel):
    name:str

@app.post("/generate_name")

def generate_name(request:gr):
    return {"message": f"Hello{request.name}"}

from pydantic import BaseModel

class ge(BaseModel):
    topic:str

@app.post("/topic_details")
def topic_details(request:ge):
    return {"received topic":request.topic}


@app.get("/user/{user_id}")

def get_id(user_id:int):
    return{"user_id":user_id, "message":"user found"}

@app.get("/search")
def search_topic(topic: str, limit: int = 5):
    return {"topic": topic, "limit": limit}
    

@app.post("/upload-pdf")
def upload_pdf(file: UploadFile = File(...)):

    if file.content_type != "application/pdf":
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are allowed"
        )
    
    upload_folder = "data/uploads"
    os.makedirs(upload_folder, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_filename = f"{timestamp}_{file.filename}"

    file_path = os.path.join(upload_folder, safe_filename)

    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
     
    return {
        "original_filename": file.filename,
        "saved_filename": safe_filename,
        "content_type": file.content_type,
        "file_path": file_path,
        "message": "File received successfully"
    }